### ISSUE TITLE
Allow to call arbitrary API endpoint

### ISSUE THREAD

**Issue by loicalbertin** [alien4cloud/alien4cloud-go-client#29]
Alien4Cloud allows to extend its REST API with plugins.
Those extensions can't be known in advance and it would be great if we can have a generic way to call them as part of this API. 

I propose to add the following functions to the client interface

```go
// Client is the client interface to Alien4cloud
type Client interface {
	NewRequest(ctx context.Context, method, urlStr string, body io.Reader, headers []Header) (*http.Request, error)
	Do(req *http.Request, data interface{}) (*http.Response, error)

	// Other functions omitted 
}
```

A non-nil data param in the Do function will allow to automatically decode json from response body in a provided struct.

Implementation would be slightly similar to a [`doWithContext` function](https://github.com/alien4cloud/alien4cloud-go-client/blob/master/alien4cloud/alien4cloud.go#L273:22) split into 2 parts which could even be refactored to use those new functions.

WDYT @laurentganne?

**Edit:** Design has slightly evolve as you can check in PR #32

**Comment by laurentganne** [comment]
👍  Excellent yes, very useful and generic way to use this client library with plugins

**Comment by loicalbertin** [comment]
Ok some few more points: 

* I think it will be better use `http.Header` instead of `[]alien4cloud.Headers` as it doesn't support multi-values for headers
* I think we can have something better for retrying errors will think about it
